name: guitar_strum_patterns
environment:
    sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2: any
  angular2_components: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  intl: ^0.14.0
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
